### ISSUE TITLE
npm 7 complains about peer dependency spec

### ISSUE THREAD

**Issue by fabien** [Janpot/next-rpc#12]
Hi, thanks for this solution.

Just tried to install it in a npm 7 monorepo setup. For some reason, the peer dependency spec `>10` does not match `10.2.3` - any thoughts? I could use `--force, or --legacy-peer-deps` but I'm sure there's a better way. How about specifying `^10`?

![image](https://user-images.githubusercontent.com/2749/119662770-08c98980-be32-11eb-9083-aaa48221e3db.png)

**Comment by Janpot** [comment]
I opened a ticket at https://github.com/npm/cli/issues/3308

**Comment by fabien** [comment]
Just wondering if you could get by with `^10` as a spec?

**Comment by Janpot** [comment]
@fabien Can you try installing `next-rpc@3.1.4`?

**Comment by fabien** [comment]
That worked, thanks for the quick fix!
