### ISSUE TITLE
Missing "typings" in package.json

### ISSUE THREAD

**Issue by jcubic** [Janpot/next-rpc#22]
I'm not 100% sure but I think that without this property in package.json you can use your types when using the library.

**Comment by jcubic** [comment]
Thanks, if you look at [NPM](https://www.npmjs.com/package/next-rpc) it shows that your library now have typescript support (TS icon).

**Comment by Janpot** [comment]
You can install `next-rpc@3.2.0-canary.0` to try it out if you want

**Comment by jcubic** [comment]
Thanks, I use `IncommingMessage` right now, it seems it working. I've only noticed that npm don't show that you have TS support.
