### ISSUE TITLE
getContext() returns empty object when function is imported from getServerSideProps

### ISSUE THREAD

**Issue by willemmulder** [Janpot/next-rpc#43]
I have an api file with next-rpc enabled. It has a function called `getAssets` which uses the `getContext` function to get the current context. I set this up in the next.config.js file.

Getting the context works properly when I import and use the `getAssets` function on the frontend, i.e. we make an API call.

Getting the context does however *not* work when I import the `getAssets` function in the `getServerSideProps` function of a page. Instead, the `getContext` function returns an empty object. Is that expected behaviour? I hoped there might be some magic that would make this work :-)

Thanks!

**Comment by willemmulder** [comment]
Note: I'm using NextJS 12.3.4 and NodeJS 18.12.1

**Comment by Janpot** [comment]
@willemmulder Doing some quick tests, looks like context doesn't get applied when `getServerSideProps` is defined as

```tsx
export const getServerSideProps = async () => {
```

or 

```tsx
export const getServerSideProps: GetServerSideProps<MyProps> = async () => {
```

It should work if you use:

```tsx
export async function getServerSideProps() {
```

Will see if I can work on a fix

**Comment by willemmulder** [comment]
@Janpot Nice find, and thanks for the fix! 

I can confirm this works :-)
